strategycfg:
  version: v3
  breakout_atr_buf: 0.40
  trail_atr_mult: 1.90
  atr_pct_max: 0.08

rs:
  filter: true
  threshold: 0.80          # concentrate to top 20% by RS (keeps turnover reasonable)
  lookback_days: 63
  index: "synthetic"       # keep what your engine actually uses

momentum:
  on: true
  pctile: 0.85             # stricter momentum gate
  lookbacks: [252, 126, 63]
  weights:  [4, 2, 1]      # tilt to 12m > 6m > 3m

regime:
  on: false                # allow entries in more conditions (often lifts CAGR on 3–5y)
